bigstack-oss/skyline-console

- .github/workflows/ci-workflows.yaml
- src/layouts/admin-menu.jsx
- src/layouts/menu.jsx
- src/stores/root.js
> chore: add github actions check

- src/components/Layout/GlobalHeader/AvatarDropdown.jsx
- src/components/Layout/GlobalHeader/ProjectDropdown.jsx
- src/components/Layout/GlobalHeader/RightContent.jsx
- src/components/Layout/GlobalHeader/index.jsx
- src/components/Layout/GlobalHeader/index.less
- src/components/Layout/GlobalNav/Right/index.jsx
- src/components/Layout/GlobalNav/Right/index.less
- src/components/Layout/GlobalNav/index.jsx
- src/components/Layout/GlobalNav/index.less
- src/components/Tables/Base/ItemActionButtons/index.jsx
- src/layouts/Base/index.less
- close #7 
- This PR is based on [PR #12](https://github.com/bigstack-oss/skyline-console/pull/12)
> feat: update header styles

- src/components/SelectLang/index.jsx
- src/components/SelectLang/index.less
- src/components/cube/CubeInput/index.jsx
- src/components/cube/CubeInput/index.less
- src/components/cube/CubePasswordInput/index.jsx
- src/components/cube/CubePasswordInput/index.less
- src/components/cube/CubeSelect/index.jsx
- src/components/cube/CubeSelect/index.less
- src/layouts/Auth/index.jsx
- src/layouts/Auth/index.less
- src/pages/auth/containers/Login/index.jsx
- src/pages/auth/containers/Login/index.less
- src/styles/base.less
- close #14 
- Create `CubeSelect`, `CubeInput` and `CubePasswordInput` components
- Update `Login` Page UI
- This PR is based on [PR #12](https://github.com/bigstack-oss/skyline-console/pull/12) and [PR #13](https://github.com/bigstack-oss/skyline-console/pull/13)
https://github.com/user-attachments/assets/7586a4d5-3eb1-45f7-a2d3-4101030724cd
> feat: update page ui - login page

- src/components/Layout/GlobalHeader/index.less
- src/layouts/Base/index.less
- src/pages/base/containers/AdminOverview/components/ComputeService.jsx
- src/pages/base/containers/AdminOverview/components/NetworkService.jsx
- src/pages/base/containers/AdminOverview/components/PlatformInfo.jsx
- src/pages/base/containers/AdminOverview/components/ResourceOverview.jsx
- src/pages/base/containers/AdminOverview/components/VirtualResource.jsx
- src/pages/base/containers/AdminOverview/index.jsx
- src/pages/base/containers/AdminOverview/style.less
- src/pages/base/containers/Overview/style.less
- close #19 
- Update `Admin Overview` Page UI
- This PR is based on [PR#13](https://github.com/bigstack-oss/skyline-console/pull/13), [PR#15](https://github.com/bigstack-oss/skyline-console/pull/15) and [PR#17](https://github.com/bigstack-oss/skyline-console/pull/17)
https://github.com/user-attachments/assets/725031b5-5811-4d2e-9009-5e8a6adce79b
> feat: update page ui - admin overview page

- src/components/Layout/GlobalHeader/index.less
- src/pages/user-center/containers/UserCenter/index.jsx
- src/pages/user-center/containers/UserCenter/styles.less
- Update `User Center` Page UI
- This PR is based on [PR#13](https://github.com/bigstack-oss/skyline-console/pull/13), [PR#15](https://github.com/bigstack-oss/skyline-console/pull/15), [PR#17](https://github.com/bigstack-oss/skyline-console/pull/17) and [PR#18](https://github.com/bigstack-oss/skyline-console/pull/18)
> feat: update page ui - user center

- src/components/FormItem/SelectTable/index.less
- src/components/MagicInput/index.jsx
- src/components/MagicInput/index.less
- src/components/Tables/Base/ActionButton/index.jsx
- src/components/Tables/Base/BatchActionButtons/index.jsx
- src/components/Tables/Base/BatchActionButtons/index.less
- src/components/Tables/Base/Download/index.jsx
- src/components/Tables/Base/ItemActionButtons/index.jsx
- src/components/Tables/Base/ItemActionButtons/index.less
- src/components/Tables/Base/PrimaryActionButtons/index.jsx
- src/components/Tables/Base/index.jsx
- src/components/Tables/Base/index.less
- src/components/cube/CubeButton/CubeCreateButton.jsx
- src/components/cube/CubeButton/CubeIconButton.jsx
- src/components/cube/CubeButton/index.less
- src/components/cube/CubePagination/index.jsx
- src/components/cube/CubePagination/index.less
- src/layouts/Base/index.less
- src/layouts/Blank/index.less
- src/resources/nova/instance.jsx
- src/styles/base.less
- src/styles/variables.less
- Update table pages UI
- This PR is based on [PR#17](https://github.com/bigstack-oss/skyline-console/pull/17), [PR#18](https://github.com/bigstack-oss/skyline-console/pull/18) and [PR#20](https://github.com/bigstack-oss/skyline-console/pull/20)
https://github.com/user-attachments/assets/7854b205-5db3-4a3b-ba36-d12934d278b6
- Every list pages
> feat: update table page UI

- src/components/Tables/Base/ActionButton/index.jsx
- src/components/Tables/Base/PrimaryActionButtons/index.jsx
- src/components/Tables/Base/index.less
- src/locales/en.json
- src/locales/ko-kr.json
- src/locales/ru.json
- src/locales/tr-tr.json
- src/locales/zh-hans.json
- src/pages/storage/containers/Volume/actions/GoToGrafana.jsx
- src/pages/storage/containers/Volume/actions/index.jsx
Close #28 
https://github.com/user-attachments/assets/b09c398b-8cb1-49ca-82c8-1afa27bba3c8
> feat: add go to grafana button in instance detail volumes tab

- src/pages/storage/containers/Volume/actions/CreateInstance.jsx
- src/stores/base.js
- src/stores/octavia/loadbalancer.js
Close #27 
https://github.com/user-attachments/assets/0b64b8ff-5813-4903-a431-77bb6379978d
> fix: pagination non-adjacent markers workaround

- src/components/Tables/Base/ItemActionButtons/index.less
- src/components/cube/CubeCopyButton/CubeCopyButton.jsx
- src/components/cube/CubeCopyButton/index.less
- src/pages/compute/containers/Instance/index.jsx
- src/pages/compute/containers/Instance/instance-table.less
Close #33 
There's no CPU & RAM usage data in API response, so total amount is displayed instead.
https://github.com/user-attachments/assets/dfd3f4f4-e917-475d-88c0-8f24d66cc6bb
> feat: instance table content update

- config/webpack.common.js
- src/components/Layout/GlobalHeader/AvatarDropdown.jsx
- src/components/Layout/GlobalHeader/index.less
- src/components/Tables/Base/index.jsx
- src/pages/compute/containers/Instance/index.jsx
- src/resources/cinder/volume-table.less
- src/resources/cinder/volume.jsx
- src/styles/base.less
Navigation failed because it was mock data:
https://github.com/user-attachments/assets/e50eff74-d710-42a8-a9c1-b2a699672928
> feat: instance detail volumes tab content update

- config/config.yaml
- config/cosApiProxy.js
- config/webpack.dev.js
- config/webpack.prod.js
- src/apis/cosApi.js
- src/apis/dataCenterApi.js
- src/apis/grafanaApi.js
- src/components/Tables/Base/ActionButton/index.jsx
- src/containers/List/index.jsx
- src/core/App.jsx
- src/pages/compute/containers/Instance/actions/GoToGrafana.jsx
- src/pages/compute/containers/Instance/index.jsx
- src/stores/datacenters/DataCenterStore.js
Close #42
Add a new property `cosApiUrl: https://..../api` to `config/config.yaml` (or `config/local_config.yaml`) to make it work.
- Hide Image column by default
https://github.com/user-attachments/assets/fd36af99-af4c-4ecd-b40b-980bcfd85b68
- Open Grafana link on "Go to Grafana" button click
https://github.com/user-attachments/assets/34afa29a-9f3c-4a16-8e3d-056ab2fe24a5
> 42 instance page issues fix

- src/pages/auth/containers/Login/index.jsx
- feature
- Set `Cube Account` the default login type
- Close #39
> 39 make `Cube Account` the default login type

- src/components/Status/index.jsx
- src/components/Tables/Base/index.jsx
- src/styles/base.less
Close #43
https://github.com/user-attachments/assets/3d3e07ea-a0bc-42ed-a974-a644254ea3b1
> 43 fix: table header and body position

- src/components/FormItem/InstanceVolume/index.jsx
- src/components/FormItem/SelectTable/index.jsx
- src/locales/en.json
- src/locales/ko-kr.json
- src/locales/ru.json
- src/locales/tr-tr.json
- src/locales/zh-hans.json
- src/locales/zh-hant.json
- src/pages/compute/containers/Instance/actions/StepCreate/BaseStep/index.jsx
- src/pages/compute/containers/Instance/actions/StepCreate/NetworkStep/index.jsx
- src/pages/compute/containers/Instance/actions/StepCreate/SystemStep/index.jsx
- src/resources/glance/image.jsx
Close #38 
The `lb-hmgr-sec-grp` security group is selected in the video just for demo purposes. In practice, it selects the first security group named `Default` (case-insensitive) if it's available.
https://github.com/user-attachments/assets/a32c87a4-a194-41e8-99fb-e145d5f569c2
> 38 adjust instance creation flow

- src/pages/compute/containers/Instance/actions/StepCreate/ConfirmStep/index.jsx
- src/pages/compute/containers/Instance/actions/StepCreate/NetworkStep/index.jsx
- src/pages/compute/containers/Instance/actions/StepCreate/SystemStep/index.jsx
- Fix
- Remove duplicate rows in Create Instance Steps
Fixes #52 
> Note
```docs
```
> fix: remove duplicate rows in Create Instance Steps

- src/pages/compute/containers/Flavor/actions/StepCreate/AccessTypeSetting.jsx
- src/pages/compute/containers/Flavor/actions/StepCreate/ParamSetting.jsx
- Fix
- Remove duplicate rows in Create Flavor Steps
https://github.com/user-attachments/assets/124a1509-cd83-4186-91dd-ca946cbb34b3
Fixes #55 
> Note
```docs
```
> 55 remove duplicate rows in Create Flavor Steps

- src/pages/auth/containers/Login/index.jsx
Close #59
https://github.com/user-attachments/assets/6af82f5a-5ff3-48aa-9124-dd70f8fc206b
> fix: login page terms and policy link

- config/config.yaml
- src/resources/nova/instance.jsx
Close #71
https://github.com/user-attachments/assets/e3c3e9ca-fcd6-4cc5-a930-3687a97a6791
> 71 fix: hide the trace column in instance details page for edge mode data center

- src/stores/base.js
Close https://github.com/bigstack-oss/cubecos/issues/92
- Before UI Update (native Skyline with broken pagination)
- There are 12 items in total, but the table only shows this if users increase items per page.
https://github.com/user-attachments/assets/d618a6ca-676f-4c2d-b711-240a98d8ffe4
- Current (pagination functionality fixed)
https://github.com/user-attachments/assets/e839de8e-e63d-4ef2-8a4e-0fc7ae929c11
> 92 fix: compute instance page pagination not clickable

- src/pages/network/containers/Topology/index.jsx
- Close https://github.com/bigstack-oss/cubecos/issues/89
1. Display external network names [5c8e832](https://github.com/bigstack-oss/skyline-console/pull/76/commits/5c8e83255411c48908cc096eee8f25b95ea103ea)
2. Update the UI to prevent overflow [7327b31](https://github.com/bigstack-oss/skyline-console/pull/76/commits/7327b314021797f0af8655781384db1703475d8f)
[Before]
https://github.com/user-attachments/assets/e8c454fe-6178-4296-a27d-46e30c5a3039
[After]
https://github.com/user-attachments/assets/59de9446-1f94-4028-8fec-70fe710af50b
> 89 topology external network

- src/components/Layout/GlobalHeader/AvatarDropdown.jsx
- src/components/Layout/GlobalHeader/index.less
Close #79
- Before
https://github.com/user-attachments/assets/e44a69cb-5ad5-423a-9fc5-bd1565e1091f
- After
https://github.com/user-attachments/assets/38829a8b-922e-44ab-9966-4cccac6fbe39
> fix: switch language menu option ellipsis

- src/containers/List/index.jsx
- src/pages/storage/containers/Backup/index.jsx
- src/pages/storage/containers/Snapshot/index.jsx
- src/pages/storage/containers/Volume/index.jsx
- src/utils/index.js
Close https://github.com/bigstack-oss/cubecos/issues/164
- Before
https://github.com/user-attachments/assets/c6e62722-14a8-42db-930c-87e9486b03ca
- After
https://github.com/user-attachments/assets/a621c823-6ccb-4b33-8aa7-58bd3e0a4658
> fix: storage volumes name search not working as expected

- src/pages/compute/containers/Image/index.jsx
- src/stores/cos/image.js
- Feature
1. Current Project Images: Displays all images under the current project, regardless of visibility.
2. Public Images: Displays images with public visibility.
3. All Images: Displays both the current project’s images and other projects’ images that have public or shared visibility.
https://github.com/user-attachments/assets/b2084301-15d5-42d5-b625-d8c7fe80f74f
- Displays all images, regardless of project or visibility.
https://github.com/user-attachments/assets/64edd8a6-9375-4b54-a169-24a43402079c
Fixes #106 
Fixes https://github.com/orgs/bigstack-oss/projects/17/views/1?filterQuery=390&pane=issue&itemId=130003813&issue=bigstack-oss%7Ccubecos%7C390
> Note
```docs
```
> 106 390 Update Image List Page Display Logic

- src/pages/compute/containers/Image/actions/Create.jsx
- fix
- Create Image with Current Project under Console View
https://github.com/user-attachments/assets/0d89073c-5c8b-4272-b37d-1d698e3aded2
Fixes #113 
> Note
```docs
```
> Fix: Create Image with Current Project under Console View
